### ISSUE TITLE
Bytes or parameters for adapter payload

### ISSUE THREAD

**Issue by noiach** [renproject/darknode-sol#58]
We have the option of requiring Shift Adapters to take in the payload as `bytes` or as arbitrary parameters:

```js
function trade(
    uint256 amount, bytes32 nHash, bytes calldata sig,
    // Payload
    uint256 relayerFee, uint256 someOtherValue
) external payable {
    verifySig(sig, abi.encode(relayerFee, someOtherValue));
    ...
}
```

or

```js
function trade(
    uint256 amount, bytes32 nHash, bytes calldata sig, bytes calldata payload
) external payable {
    [uint256 relayerFee, uint256 someOtherValue] = abi.decode(payload);
    verifySig(sig, payload);
    ...
}
```

**Comment by loongy** [comment]
I think we should test both approaches and see whether or not `abi.encode` or `abi.decode` costs more gas. The one that is cheaper will dictate which approach we take.

**Comment by loongy** [comment]
Ok, so after some discussion in the team, let's go with:

```
function trade(
    uint256 amount, bytes32 nHash, bytes calldata sig,
    // Payload
    uint256 relayerFee, uint256 someOtherValue
) external payable {
    verifySig(sig, abi.encode(relayerFee, someOtherValue));
    ...
}
```

The main reason for this decision is that: in order to understand the signature of the function, the function does not have to bleed implementation details. Seeing a `payload` is very opaque. Services like etherscan have no chance to "decode" the meaning. Whereas a list of explicit arguments can be understood out of context _and_ in context.
